#include <iostream>
#include <algorithm>
#include <functional>

template<typename T, typename S, typename F>
std::vector<T> real_transform(S thing, F f) {
	std::vector<T> temp (100);
	std::transform(thing.begin(), thing.end(), temp.begin(), f);
	return temp;
}
int main(void) {
	//utflag{shouldve_used_haskell_thonk}
	std::cout << "Transform! ";
	std::string input;
	std::cin >> input;
	std::vector<int> f (100);
	f = real_transform<int, std::string, std::function<int(char)>>(input, [] (char c) -> int {return (int)c; });
	f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n + 40; });
	f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 43; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 172; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 1059; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 41769; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 52582; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 53683; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 62424; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 61360; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 63137; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 38153; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 43166; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 20145; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 10689; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 245; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 33983; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 43048; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 11902; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 59535; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 47041; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 44744; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 17887; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 7377; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 36893; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 13938; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 26445; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 46214; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 38543; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 12072; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 2189; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 54800; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 27654; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 7431; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 332; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 56457; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 4744; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 57081; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 59623; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 38282; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 45; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 53171; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 41682; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 7076; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 31046; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 63027; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 65221; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 55242; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 9882; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 13150; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 35181; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 64203; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 11650; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 28581; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 2384; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 29937; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 23617; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 36515; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 1837; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 9928; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 54332; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 53571; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 23444; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 27692; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 52514; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 23974; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 15414; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 7863; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 59324; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 55911; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 23224; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 53850; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 57592; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 24808; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 45122; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 64033; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 55503; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 47467; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 30472; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 61619; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 40686; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 19383; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 51282; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 45990; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 25211; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 23881; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 50300; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 13975; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 7120; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 41056; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 24358; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 4955; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 62581; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 51934; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 1869; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 47538; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 16923; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 24733; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 60594; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 39360; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 19368; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 7443; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 35422; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 33264; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 45481; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 36722; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 5477; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 42069; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 4434; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 60987; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 57345; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 50212; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 4457; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 10678; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 3928; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 37265; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 36481; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 50756; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 44754; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 27064; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 37053; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 33895; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 61109; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 59457; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 20557; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 16697; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 54955; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 17301; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 1532; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 38290; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 13059; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 42858; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 40669; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 24154; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 58923; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 15962; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 39995; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 51951; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 16841; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 10539; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 33012; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 9377; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 46553; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 13123; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 25353; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 48410; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 41754; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 40673; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 14438; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 40742; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 62354; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 63231; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 13781; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 115; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 34864; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 26210; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 32488; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 46182; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 48683; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 38735; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 31883; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 15836; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 5665; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 25482; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 37926; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 42618; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 60668; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 52843; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 21925; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 56540; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 10616; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 43459; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 12700; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 32137; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 47922; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 6671; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 41638; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 21342; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 9437; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 19680; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 65418; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 34373; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 32488; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 2011; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 30703; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 59983; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 32288; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 60789; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 40057; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 22989; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 6164; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 56774; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 53466; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 22185; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 54841; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 64454; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 16662; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 796; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 34215; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 1953; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 58425; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 25987; });
f = real_transform<int, std::vector<int>, std::function<int(int)>>(f, [] (int n) -> int {return n ^ 15603; });

	auto v = f.begin();
	for(int i = 0; i < 35; i++) {
		std::cout << *v;
		v++;
	}
	std::cout << '\n';
	return 0;
}
