version: "3.8"
services:
  pwn-shellcode:
    build:
      context: .
      args: 
        USER: "shell"
        FLAG: "utflag{i_should_be_doing_ccdc_rn}"
    deploy:
      replicas: 1
    ports:
      - "9009:9000"
    read_only: true
    